"""Service layer that adapts AiZynthFinder to HTTP requests."""

from __future__ import annotations

import base64
import io
import threading
import time
from pathlib import Path
from typing import Any

from .models import (
    MetadataResponse,
    RouteResult,
    SearchDefaults,
    SearchRequest,
    SearchResponse,
)
from .settings import Settings


class ServiceNotReadyError(RuntimeError):
    """Raised when the AiZynthFinder engine cannot be used yet."""


class RetrosynthesisService:
    """Thin wrapper around the official AiZynthFinder Python API."""

    def __init__(self, settings: Settings) -> None:
        self._settings = settings
        self._metadata_lock = threading.Lock()
        self._metadata_cache: MetadataResponse | None = None

    def metadata(self) -> MetadataResponse:
        """Return available stocks, policies and scorers for the configured engine."""

        readiness_message = self._readiness_message()
        if readiness_message:
            return MetadataResponse(
                ready=False,
                message=readiness_message,
                config_path=str(self._settings.config_path)
                if self._settings.config_path
                else None,
            )

        with self._metadata_lock:
            if self._metadata_cache:
                return self._metadata_cache

            try:
                finder = self._new_finder()
            except Exception as err:  # pragma: no cover - depends on local model files
                return MetadataResponse(
                    ready=False,
                    message=f"Unable to initialize AiZynthFinder: {err}",
                    config_path=str(self._settings.config_path),
                )

            rewards = list(
                finder.config.search.algorithm_config.get("search_rewards", [])
            )
            self._metadata_cache = MetadataResponse(
                ready=True,
                config_path=str(self._settings.config_path),
                stocks=list(finder.stock.items),
                expansion_policies=list(finder.expansion_policy.items),
                filter_policies=list(finder.filter_policy.items),
                scorers=list(finder.scorers.names()),
                defaults=SearchDefaults(
                    time_limit=int(finder.config.search.time_limit),
                    iteration_limit=int(finder.config.search.iteration_limit),
                    max_transforms=int(finder.config.search.max_transforms),
                    return_first=bool(finder.config.search.return_first),
                    rewards=rewards,
                ),
            )
            return self._metadata_cache

    def search(self, request: SearchRequest) -> SearchResponse:
        """Run a retrosynthesis search and serialize route data for the frontend."""

        readiness_message = self._readiness_message()
        if readiness_message:
            raise ServiceNotReadyError(readiness_message)

        finder = self._new_finder()
        self._apply_request_options(finder, request)

        started = time.perf_counter()
        finder.target_smiles = request.smiles
        finder.prepare_tree()
        finder.tree_search(show_progress=False)

        rewards = request.rewards or finder.config.search.algorithm_config.get(
            "search_rewards", []
        )
        finder.build_routes(scorer=request.route_scorer or rewards or None)
        if len(finder.routes) > 0:
            finder.routes.compute_scores(*finder.scorers.objects())
        statistics = finder.extract_statistics()
        stock_info = finder.stock_info()

        route_dicts = finder.routes.dict_with_extra(
            include_metadata=True, include_scores=True
        )
        route_images, warnings = self._make_route_images(finder)
        routes = [
            self._route_result(index, tree, route_images[index - 1])
            for index, tree in enumerate(route_dicts, start=1)
        ]

        return SearchResponse(
            target=finder.target_smiles,
            elapsed_seconds=time.perf_counter() - started,
            statistics=statistics,
            stock_info=stock_info,
            routes=routes,
            warnings=warnings,
        )

    def _readiness_message(self) -> str | None:
        config_path = self._settings.config_path
        if not config_path:
            return (
                "Set AIZYNTH_CONFIG to an AiZynthFinder config.yml generated by "
                "`download_public_data <folder>` before running searches."
            )
        if not Path(config_path).exists():
            return f"AiZynthFinder config file was not found: {config_path}"
        try:
            self._aizynthfinder_class()
        except ImportError as err:
            return (
                "AiZynthFinder could not be imported. Ensure the Python package "
                "`aizynthfinder` and its native runtime libraries are installed "
                f"(for Docker this includes libXrender/libXext/libSM/libGL): {err}"
            )
        return None

    def _new_finder(self) -> Any:
        finder_cls = self._aizynthfinder_class()
        return finder_cls(configfile=str(self._settings.config_path))

    @staticmethod
    def _aizynthfinder_class() -> Any:
        from aizynthfinder.aizynthfinder import AiZynthFinder

        return AiZynthFinder

    def _apply_request_options(self, finder: Any, request: SearchRequest) -> None:
        stocks = request.stocks or list(finder.stock.items)
        finder.stock.select(stocks)
        finder.stock.set_stop_criteria({"counts": request.atom_limits})

        expansion = request.expansion_policies or list(finder.expansion_policy.items[:1])
        if expansion:
            finder.expansion_policy.select(expansion)

        if request.filter_policies:
            finder.filter_policy.select(request.filter_policies)
        else:
            finder.filter_policy.deselect()

        finder.config.search.time_limit = min(
            request.time_limit, self._settings.max_time_seconds
        )
        finder.config.search.iteration_limit = min(
            request.iteration_limit, self._settings.max_iterations
        )
        finder.config.search.max_transforms = request.max_transforms
        finder.config.search.return_first = request.return_first
        finder.config.search.algorithm = "mcts"

        rewards = request.rewards or finder.config.search.algorithm_config.get(
            "search_rewards", []
        )
        if rewards:
            finder.config.search.algorithm_config["search_rewards"] = rewards

    @staticmethod
    def _make_route_images(finder: Any) -> tuple[list[str | None], list[str]]:
        warnings: list[str] = []
        route_count = len(finder.routes)
        images: list[str | None] = [None] * route_count
        if route_count == 0:
            return images, warnings
        try:
            finder.routes.make_images()
            for index, image in enumerate(finder.routes.images):
                if image is None:
                    continue
                buffer = io.BytesIO()
                image.save(buffer, format="PNG")
                encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
                images[index] = f"data:image/png;base64,{encoded}"
        except Exception as err:  # pragma: no cover - optional chemistry rendering
            warnings.append(f"Route image rendering unavailable: {err}")
        return images, warnings

    @staticmethod
    def _route_result(index: int, tree: dict[str, Any], image: str | None) -> RouteResult:
        metadata = dict(tree.get("metadata") or tree.get("route_metadata") or {})
        scores = dict(tree.get("scores") or {})
        return RouteResult(
            index=index,
            is_solved=bool(metadata.get("is_solved", tree.get("in_stock", False))),
            scores=scores,
            metadata=metadata,
            tree=tree,
            image=image,
        )
